/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 2
 */


export namespace AutoFillTurboModule {
  export const NAME = 'AutoFillTurboModule' as const

  export interface Spec {
    autoSave(onSuccess: () => void, onFailure: () => void): void;

  }
}
