/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 2
 */
#pragma once

#include "RNOH/Package.h"
#include "RNOH/ArkTSTurboModule.h"
#include "AutoFillTurboModule.h"

namespace rnoh {

class AutoFillPackageTurboModuleFactoryDelegate : public TurboModuleFactoryDelegate {
  public:
    SharedTurboModule createTurboModule(Context ctx, const std::string &name) const override {
        if (name == "AutoFillTurboModule") {
            return std::make_shared<AutoFillTurboModule>(ctx, name);
        }
        return nullptr;
    };
};

class AutoFillPackage : public Package {
  public:
    AutoFillPackage(Package::Context ctx) : Package(ctx){};

    std::unique_ptr<TurboModuleFactoryDelegate> createTurboModuleFactoryDelegate() override {
        return std::make_unique<AutoFillPackageTurboModuleFactoryDelegate>();
    }
};

} // namespace rnoh
