
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 2
 */
#include "AutoFillTurboModule.h"

namespace rnoh {
using namespace facebook;

AutoFillTurboModule::AutoFillTurboModule(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_METHOD_METADATA(autoSave, 2),
    };
}

} // namespace rnoh
