#include "RNOH/PackageProvider.h"
#include "generated/RNOHGeneratedPackage.h"
#include "AutoFillPackage.h"
#include "GestureHandlerPackage.h"
#include "SafeAreaViewPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  return {
      std::make_shared<RNOHGeneratedPackage>(ctx), // generated by codegen v1
      std::make_shared<AutoFillPackage>(ctx),
      std::make_shared<GestureHandlerPackage>(ctx),
      std::make_shared<SafeAreaViewPackage>(ctx),

  };
}